name = "w3name-staging"
main = "dist/index.mjs"
compatibility_date = "2022-06-10"

[build]
command = "npm run build"

[durable_objects]
bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
]

[[migrations]]
tag = "v1"
new_classes = ["NameRoom0", "IPNSRecord"]