name = "w3name"
main = "dist/index.mjs"
compatibility_date = "2022-06-10"

[build]
command = "npm run build"

[[migrations]]
tag = "v1"
new_classes = ["NameRoom0", "IPNSRecord"]

# For the dev environment. The "durable_objects" section is not shared among environments though.
[durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" },
    { name = "METRICS_STORE", class_name = "MetricsStore" }
  ]

[[queues.producers]]
queue = "metrics-updates"
binding = "METRICS_QUEUE"

[[queues.consumers]]
  queue = "metrics-updates"
  # The maximum number of messages allowed in each batch. This can be pretty large, as we're just
  # adding the values from the messages together.
  max_batch_size = 1000
  # The maximum number of seconds to wait until a batch is full. This should be fairly frequent so
  # that we're updating the stats at least as often as Prometheus is fetching them from us.
  max_batch_timeout = 5
  max_retries = 10
  dead_letter_queue = "metrics-updates-dlq"

[vars]
REBROADCAST_INTERVAL_MS = "600000"
PUBLISHER_ENDPOINT_URL = "http://127.0.0.1:8000"
PUBLISHER_AUTH_SECRET = "123456"

# Test

[env.test.vars]
REBROADCAST_INTERVAL_MS = "500"
PUBLISHER_ENDPOINT_URL = "http://127.0.0.1:8000"
PUBLISHER_AUTH_SECRET = "123456"

[env.test.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" },
    { name = "METRICS_STORE", class_name = "MetricsStore" }
  ]

# Staging

[env.staging]
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "https://name-staging.web3.storage/*", zone_id = "7eee3323c1b35b6650568604c65f441e" }
]
vars = { ENV = "staging", REBROADCAST_INTERVAL_MS = "86400000" }
[env.staging.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# Production

[env.production]
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "https://name.web3.storage/*", zone_id = "7eee3323c1b35b6650568604c65f441e" }
]
vars = { ENV = "production", REBROADCAST_INTERVAL_MS = "86400000" }
[env.production.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" },
    { name = "METRICS_STORE", class_name = "MetricsStore" }
  ]

# The necessary secrets are:
# - PUBLISHER_ENDPOINT_URL
# - PUBLISHER_AUTH_SECRET
# - LOGTAIL_TOKEN
# - SENTRY_DSN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
