name = "w3name"
main = "dist/index.mjs"
compatibility_date = "2022-06-10"

[build]
command = "npm run build"

[[migrations]]
tag = "v1"
new_classes = ["NameRoom0", "IPNSRecord"]

# Test

[env.test.vars]
REBROADCAST_INTERVAL_MS = 500
PUBLISHER_ENDPOINT_URL = "http://127.0.0.1:8000"
PUBLISHER_AUTH_SECRET = 123456

# Staging

[env.staging]
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "https://name-staging.web3.storage/*", zone_id = "7eee3323c1b35b6650568604c65f441e" }
]
vars = { ENV = "staging" }
[env.staging.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]

# Production

[env.production]
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
routes = [
  { pattern = "https://name.web3.storage/*", zone_id = "7eee3323c1b35b6650568604c65f441e" }
]
vars = { ENV = "production" }
[env.production.durable_objects]
  bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
  ]
