name = "api"
main = "dist/index.mjs"
compatibility_date = "2022-06-10"

[build]
command = "npm run build"

[build.upload]
dir = "dist"
main = "index.mjs"
format = "modules"

[durable_objects]
bindings = [{ name = "NAME_ROOM", class_name = "NameRoom0" }]

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true