name = "w3name"
main = "dist/index.mjs"
compatibility_date = "2022-06-10"

[build]
command = "npm run build"

[durable_objects]
bindings = [
    { name = "NAME_ROOM", class_name = "NameRoom0" },
    { name = "IPNS_RECORD", class_name = "IPNSRecord" }
]

[env.test.vars]
REBROADCAST_INTERVAL_MS = 500
PUBLISHER_ENDPOINT_URL = "http://127.0.0.1:8000"
PUBLISHER_AUTH_SECRET = 123456

[[migrations]]
tag = "v1"
new_classes = ["NameRoom0", "IPNSRecord"]

[env.production]
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
# TODO: confirm and add correct route URL
route = "https://w3name-production.protocol-labs.workers.dev/*"
route = "https://w3name.web3.storage/*"
vars = { ENV = "production" }

[env.staging]
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
# TODO: confirm and add correct route URL
route = "https://w3name-staging.protocol-labs.workers.dev/*"
route = "https://staging.w3name.web3.storage/*"
vars = { ENV = "staging" }
