name: Api
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - '.github/workflows/api.yml'
  pull_request:
    types:
      - opened
      # Triggered when a pull request's head branch is updated.
      # For example, when the head branch is updated from the base branch, when new commits are pushed to the head branch, or when the base branch is changed.
      - synchronize

    paths:
      - 'packages/api/**'
      - '.github/workflows/api.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: npm run lint --workspace packages/api
      - run: npm run build --workspace packages/api
      - run: npm test --workspace packages/api

